### ISSUE TITLE
Using ExtraArgs with buckshot solver

### ISSUE THREAD

**Issue by tasseff** [uqfoundation/mystic#122]
I'm trying to use the buckshot-Powell solver but am encountering difficulties when the objective function requires extra arguments. I've adapted `examples/buckshot_example06.py` to form a new example that produces an error:

```python
# the Buckshot solver
from mystic.solvers import BuckshotSolver

# Powell's Directonal solver
from mystic.solvers import PowellDirectionalSolver

# Chebyshev polynomial and cost function
from mystic.models.poly import chebyshev8, chebyshev8cost
from mystic.models.poly import chebyshev8coeffs

# if available, use a pathos worker pool
try:
    from pathos.pools import ProcessPool as Pool
   #from pathos.pools import ParallelPool as Pool
except ImportError:
    from mystic.pools import SerialPool as Pool

# tools
from mystic.termination import NormalizedChangeOverGeneration as NCOG
from mystic.math import poly1d
from mystic.monitors import VerboseLoggingMonitor
from mystic.tools import getch

def chebyshev8cost_mod(x, foo, bar):
    return chebyshev8cost(x)

if __name__ == '__main__':
    from pathos.helpers import freeze_support, shutdown
    freeze_support() # help Windows use multiprocessing

    # dimensional information
    from mystic.tools import random_seed
    random_seed(123)
    ndim = 9
    npts = 8

    # configure monitor
    stepmon = VerboseLoggingMonitor(1,2)

    # use buckshot-Powell to solve 8th-order Chebyshev coefficients
    solver = BuckshotSolver(ndim, npts)
    solver.SetNestedSolver(PowellDirectionalSolver)
    solver.SetMapper(Pool().map)
    solver.SetGenerationMonitor(stepmon)
    solver.SetStrictRanges(min=[-300]*ndim, max=[300]*ndim)
    solver.Solve(chebyshev8cost_mod, NCOG(1e-4), disp=1, ExtraArgs=(1, 2))
    solution = solver.Solution()
    shutdown() # help multiprocessing shutdown all workers
```

This produces `TypeError: function_wrapper() takes at most 1 arguments (3 given)`. Any ideas?

**Comment by mmckerns** [comment]
Confirmed.  There's a bug somewhere, where `ExtraArgs` is not propagated correctly.
```
>>> solver.Solve(chebyshev8cost_mod, NCOG(1e-4), disp=1, ExtraArgs=(1, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_solver.py", line 937, in Solve
    self._Solve(cost, ExtraArgs, **settings)
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_ensemble_solver.py", line 651, in _Solve
    results = list(self._map(_solve, op, iv, vb, cb, **self._mapconfig))
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/python_map.py", line 66, in python_map
    result = list(map(func, *arglist)) #     see pathos.pyina.ez_map
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_ensemble_solver.py", line 636, in _solve
    solver.Solve(cost,ExtraArgs=ExtraArgs,disp=disp,callback=callback)
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/scipy_optimize.py", line 686, in Solve
    ExtraArgs, **kwds)
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_solver.py", line 932, in Solve
    cost = self._bootstrap_objective(cost, ExtraArgs)
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_solver.py", line 736, in _bootstrap_objective
    self.SetObjective(cost, ExtraArgs)
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/abstract_solver.py", line 595, in SetObjective
    validate(cost, None, *args)
  File "/Users/mmckerns/lib/python2.7/site-packages/klepto-0.1.8-py2.7.egg/klepto/_inspect.py", line 217, in validate
    raise TypeError("%s() takes at most %d arguments (%d given)" % (func.__name__, len(named)+len(p_args), len(p_args)+len(args)+len(kwds)))
TypeError: function_wrapper() takes at most 1 arguments (3 given)
```
I'd suggest working around it for the moment, by producing a cost function with one input.
I'll work on a patch.

**Comment by mmckerns** [comment]
the patch is a bit of a hack to enable SetNestedSolver to "work" for both solver instances and solver classes being passed... but all tests pass now, examples work, etc.  May be some funny business when passing a nested configured solver... but that's for another issue.

**Comment by mmckerns** [comment]
FYI: there's another potential workaround that I didn't mention (it's a mostly developed feature, actually).  If you pass `step=True` (or do `solver.Step()` before `solver.Solve()`), the ensemble solvers will run non-blocking instead of the default (which is each of the nested solvers run in a blocking fashion to the end).

**Comment by tasseff** [comment]
Great, thank you! I ended up refactoring to not require ExtraArgs, but I see where this could come in handy.
