### ISSUE TITLE
should penalty functions ever throw a ZeroDivisionError?

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#124]
Should penalty functions be allowed to throw a `ZeroDivisonError`, or should they produce an `inf` penalty (or similar) in that case?

```
>>> equations = """
... x0 * x1 * x2 <= -0.75
... """
>>> import mystic.symbolic as ms
>>> from mystic.constraints import and_ as _and, or_ as _or
>>> eqns = ms.simplify(equations)
>>> print(eqns)
x1 > 0
x2 > 0
x0 <= -0.75/(x1*x2)
>>> pens = ms.generate_penalty(ms.generate_conditions(eqns))
>>> pens([0, 1, 1])
112.5
>>> pens([1, 0, 1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.3.6.dev0-py2.7.egg/mystic/penalty.py", line 350, in func
    pf = condition(x, *args, **kwds)
  File "<string>", line 2, in inequality_4429004912
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero
>>>
```

**Comment by mmckerns** [comment]
similar to #123
