### ISSUE TITLE
TypeError from sympy in example2/g03.py 

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#149]
```
$ python g03.py 
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 724, in solve
    if not soln: raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g03.py", line 60, in <module>
    cf = cf(len(x))
  File "g03.py", line 50, in cf
    return generate_constraint(generate_solvers(solve(equations(len))))
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 727, in solve
    target=target, **kwds)
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 915, in _solve_nonlinear
    mysoln = _solve_single(eqn, variables=varname, target=_target, warn=warn, locals=locals, **kwarg)
  File "<string>", line 165, in _solve_single
  File "<string>", line 12, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sympy/core/expr.py", line 358, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
```

**Comment by mmckerns** [comment]
generally it's better to use `mystic.constraints.simplify` instead of `mystic.constraints.solve` when building constraints from symbolic equations.
