### ISSUE TITLE
simplify incorrectly parses leading zero for float between 0 and 1

### ISSUE THREAD

**Issue by zhugeyicixin** [uqfoundation/mystic#163]
mystic==0.3.8 works for `simplify('x = 0.1',['x'])` and `simplify('x = .01',['x'])`.
However, when I use `simplify('x = 0.01',['x'])`, there is an error as following. I believe it is a bug.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/software/anaconda3/envs/py37/lib/python3.7/site-packages/mystic/symbolic.py", line 748, in simplify
    cons = [simple(ci, **kwds) for ci in cons] if type(cons) is tuple else simple(cons, **kwds)
  File "<string>", line 120, in _simplify
  File "<string>", line 42, in _simplify1
  File "/home/software/anaconda3/envs/py37/lib/python3.7/site-packages/mystic/_symbolic.py", line 727, in solve
    target=target, **kwds)
  File "/home/software/anaconda3/envs/py37/lib/python3.7/site-packages/mystic/_symbolic.py", line 893, in _solve_nonlinear
    invertedstring = _solve_single(eqn, variables=varname, target=_target, warn=warn, locals=locals, **kwarg)
  File "<string>", line 163, in _solve_single
  File "<string>", line 3
    eq1= Eq(_0 , 01)
```

**Comment by mmckerns** [comment]
It's only when the float has a leading `0.`.
```
Python 3.7.12 (default, Nov 11 2021, 17:34:58) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mystic as my
>>> my.symbolic.simplify('x = 1.001', ['x'])
'x = 1.00100000000000'
>>> my.symbolic.simplify('x = -0.001', ['x'])
'x = -0.00100000000000000'
>>> my.symbolic.simplify('x = .001', ['x'])
'x = 0.00100000000000000'
>>> my.symbolic.simplify('x = 0.001', ['x'])
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 713, in solve
    target=target, **kwds)
  File "<string>", line 163, in _solve_single
  File "<string>", line 3
    eq1= Eq(_0 , 001)
                   ^
SyntaxError: invalid token
```

**Comment by zhugeyicixin** [comment]
Yes. Is there any reason for that?

**Comment by mmckerns** [comment]
No... I actually noticed this behavior very recently.  It surprised me... but I was busy trying to solve a problem, and I forgot to look into it.  🤦  So, thanks for the "reminder".  I'll see what is causing the parsing issue.

**Comment by zhugeyicixin** [comment]
Thank you very much!

**Comment by mmckerns** [comment]
Expected behavior:
```
>>> my.symbolic.solve('x = .001', verbose=True)
rand = Symbol('rand')
eq1= Eq(x , .001)
_xlist = ()
_elist = [symsol([eq1], [i], **symsol_kwds) for i in _xlist]
_elist = [i if isinstance(i, dict) else {j:i[-1][-1]} for j,i in zip(_xlist,_elist) if i]
soln = dict()
[soln.update(i) for i in _elist if i]

{}
rand = Symbol('rand')
eq1= Eq(x , .001)
_xlist = ()
_elist = [symsol([eq1], [i], **symsol_kwds) for i in _xlist]
_elist = [i if isinstance(i, dict) else {j:i[-1][-1]} for j,i in zip(_xlist,_elist) if i]
soln = dict()
[soln.update(i) for i in _elist if i]

{}
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 724, in solve
    if not soln: raise ValueError
ValueError
```

Bad behavior:
```
>>> my.symbolic.solve('x = 0.001', verbose=True)
rand = Symbol('rand')
eq1= Eq(x , 001)
_xlist = ()
_elist = [symsol([eq1], [i], **symsol_kwds) for i in _xlist]
_elist = [i if isinstance(i, dict) else {j:i[-1][-1]} for j,i in zip(_xlist,_elist) if i]
soln = dict()
[soln.update(i) for i in _elist if i]

Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.7/site-packages/mystic-0.3.9.dev0-py3.7.egg/mystic/_symbolic.py", line 713, in solve
    target=target, **kwds)
  File "<string>", line 163, in _solve_single
  File "<string>", line 2
    eq1= Eq(x , 001)
                  ^
SyntaxError: invalid token
```

**Comment by zhugeyicixin** [comment]
Super fast! Thank you very much!
