### ISSUE TITLE
> 10 named variables causes NameError in simplify

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#198]
Reported here: https://stackoverflow.com/q/75550369/2379433

```
>>> import mystic.symbolic as ms
>>> equations = """A + B + C + D + E + F + G + H + I + J  < 1000"""
>>> var = list('ABCDEFGHIJKLMNOPQ')
>>> eqns = ms.simplify(equations, variables=var, all=True)
>>> print(eqns)
A < -B - C - D - E - F - G - H - I - J + 1000
```
However, adding another variable causes an error:
```
>>> import mystic.symbolic as ms
>>> equations = """A + B + C + D + E + F + G + H + I + J + x0 + x1 < 1000"""
>>> var = list('ABCDEFGHIJ') + ['x0','x1']
>>> eqns = ms.simplify(equations, variables=var, all=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.8/site-packages/mystic/symbolic.py", line 806, in simplify
    cons = [simple(ci, **kwds) for ci in cons] if type(cons) is tuple else simple(cons, **kwds)
  File "/Users/mmckerns/lib/python3.8/site-packages/mystic/symbolic.py", line 762, in _simplify
    res = _simplify1(eqn, variables=variables, target=vars, **kwds)
  File "/Users/mmckerns/lib/python3.8/site-packages/mystic/symbolic.py", line 735, in _simplify1
    if equals(before,after,next(testvals),**kwds):
  File "/Users/mmckerns/lib/python3.8/site-packages/mystic/symbolic.py", line 449, in equals
    after, before = eval(after,{},locals_), eval(before,{},locals_)
  File "<string>", line 1, in <module>
NameError: name 'B0' is not defined
```
In particular, the second variable appears to get parsed incorrectly where something like `_10` becomes `B0`.

If you include an appropriately named variable (related to the 2nd variable), then no error:
```
>>> equations = """x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11 < 1000"""
>>> var = ['x%s' % i for i in range(12)]
>>> eqns = ms.simplify(equations, variables=var, all=True)
>>> print(eqns)
x0 < -x1 - x10 - x11 - x2 - x3 - x4 - x5 - x6 - x7 - x8 - x9 + 1000
>>> equations = """A + B + C + D + E + F + G + H + I + J + B0 + B1 < 1000"""
>>> var = list('ABCDEFGHIJ') + ['B0','B1']
>>> eqns = ms.simplify(equations, variables=var, all=True)
>>> print(eqns)
A < -B - B0 - B1 - C - D - E - F - G - H - I - J + 1000
```

**Comment by mmckerns** [comment]
When using `verbose=True`, it can be seen that:
```
{_0: -_1 - _10 - _2 - _3 - _4 - _5 - _6 - _7 - _8 - _9 + 1000}
in: A + B + C + D + E + F + G + H + I + J + K < 1000
out: A < -B - B0 - C - D - E - F - G - H - I - J + 1000
```
...so, `_10` gets parsed as `_1` then `0` (i.e. `B0`).
I potentially parsing in decreasing order should solve the issue.
