### ISSUE TITLE
test failures for python 2.5

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#42]
```
dude@hilbert>$ python test_symbolic_basic.py 
Traceback (most recent call last):
  File "test_symbolic_basic.py", line 181, in <module>
    test_matrix_interface()
  File "test_symbolic_basic.py", line 136, in test_matrix_interface
    assert almostEqual(cf(x0), 0.133687558709, tol=1e-15)
AssertionError
dude@hilbert>$ python test_compound_termination.py 
Traceback (most recent call last):
  File "test_compound_termination.py", line 200, in <module>
    test_me(False)
  File "test_compound_termination.py", line 71, in test_me
    assert _v.index(v) == _c.index(c) == _n.index(n) == 0
AttributeError: 'When' object has no attribute 'index'
```

**Comment by mmckerns** [comment]
Fixed in e46fbec6beb986c5aa21e4de757501b98e47b309
