### ISSUE TITLE
clarify differences and similarities for Lnorm and minkowski

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#71]
`Lnorm` and `minkowski` (and related) are similar… should state how, and resolve any unintended differences.  For example:

```
>>> x = np.array([1,2,3,4,5])
>>>
>>> md.Lnorm(x, p=100) #XXX: wrong?
1.0
>>> md.minkowski(x, np.zeros_like(x), p=100, up=False) #XXX: wrong?
1.0
>>>
>>> md.Lnorm(x, p=3)
6.082201995573399
>>> md.minkowski(x, np.zeros_like(x), up=False)
6.0822019955733992
>>> md.minkowski(x, np.zeros_like(x), p=3, up=False)
6.0822019955733992
>>>
>>> md.Lnorm(x, p=2)
7.416198487095663
>>> md.euclidean(x, np.zeros_like(x), up=False)
7.416198487095663
>>> md.minkowski(x, np.zeros_like(x), p=2, up=False)
7.416198487095663
>>>
>>> md.Lnorm(x, p=1)
15.0
>>> md.manhattan(x, np.zeros_like(x), up=False)
15.0
>>> md.minkowski(x, np.zeros_like(x), p=1, up=False)
15.0
>>>
>>> #FIXME: shouldn't barf; XXX: zero norm?
>>> md.Lnorm(x, p=0)
5.0
>>> md.chebyshev(x, np.zeros_like(x), up=False)
5
>>> md.minkowski(x, np.zeros_like(x), p=0, up=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.2a2.dev0-py2.7.egg/mystic/math/distance.py", line 165, in minkowski
    return sum(d**p, axis=axis)**(1./p)
ZeroDivisionError: float division by zero
```

More generally:
```
>>> y = np.array([5,3,8,9,-2,-4,-10])
>>>
>>> #FIXME: shouldn't barf; #XXX: shouldn't nan?
>>> md.Lnorm(y, p=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic-0.2a2.dev0-py2.7.egg/mystic/math/distance.py", line 25, in Lnorm
    w = float(sum(abs(weights**p)))**(1./p)
ValueError: negative number cannot be raised to a fractional power
>>> md.minkowski(y, np.zeros_like(y), p=100, up=False)
nan
>>>
>>> md.Lnorm(y, p=3)
13.50845378144636
>>> md.minkowski(y, np.zeros_like(y), p=3, up=False)
13.508453781446359
>>>
>>> md.Lnorm(y, p=2)
17.291616465790582
>>> md.minkowski(y, np.zeros_like(y), p=2, up=False)
17.291616465790582
>>>
>>> md.Lnorm(y, p=1)
41.0
>>> md.minkowski(y, np.zeros_like(y), p=1, up=False)
41.0
>>>
>>> md.Lnorm(y, p=0)
7.0
>>> md.chebyshev(y, np.zeros_like(y), up=False)
10

>>> z = np.array([0,1,5,6])
>>>
>>> md.Lnorm(z, p=0)
3.0
>>> md.chebyshev(z, np.zeros_like(z), up=False)
6
```

**Comment by mmckerns** [comment]
fixed in 3a1b59838e75c0dcd8041016c5e8e3ac2d17e6d3
