### ISSUE TITLE
interactive plotting examples fail for python 2.7

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#96]
For python 2.7, several of the examples with interactive plotting are now failing.  Looks like a backward incompatible change to `matplotlib` is the culprit.

```
>$ python example06.py 
Powell's Method
===============
Traceback (most recent call last):
  File "example06.py", line 71, in <module>
    plot_exact()
  File "example06.py", line 33, in plot_exact
    pylab.title("fitting 8th-order Chebyshev polynomial coefficients")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1382, in title
    return gca().set_title(s, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 959, in gca
    return gcf().gca(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 588, in gcf
    return figure()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 556, in figure
    draw_if_interactive()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 185, in draw_if_interactive
    cls.trigger_manager_draw(manager)
TypeError: unbound method trigger_manager_draw() must be called with _BackendMac instance as first argument (got FigureManagerMac instance instead)
```

**Comment by mmckerns** [comment]
Seems to be completely a `matplotlib` bug:
```
>$ python
Python 2.7.14 (default, Sep 22 2017, 00:06:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> plt.ioff()
>>> plt.figure()
<matplotlib.figure.Figure object at 0x10f576810>
>>> plt.show()
>>> plt.ion()
>>> plt.figure()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 556, in figure
    draw_if_interactive()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 185, in draw_if_interactive
    cls.trigger_manager_draw(manager)
TypeError: unbound method trigger_manager_draw() must be called with _BackendMac instance as first argument (got FigureManagerMac instance instead)
```

**Comment by mmckerns** [comment]
Apparently this issue is already fixed (see: https://github.com/matplotlib/matplotlib/issues/9345), and a patch in an upcoming bug fix release.
